services:
  fastapi:
    build: .
    env_file: "./.env"
    networks:
        - point-system
    ports:
        - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    env_file: "./.env"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
        - point-system
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10
      interval: 5s
      start_period: 30s

volumes:
  db_data: 

networks:
  point-system:
    driver: bridge
